// <auto-generated />
namespace ProvaOO2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class xii : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(xii));
        
        string IMigrationMetadata.Id
        {
            get { return "201907032319201_xii"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
